/*
 * Auto-generated by CMake — do not edit.
 * Zephyr platform equivalent of Meson-generated claw_gen_config.h.
 * Only defines macros when environment variables are non-empty.
 */

#ifndef CLAW_GEN_CONFIG_H
#define CLAW_GEN_CONFIG_H

#define RT_CLAW_VERSION "0.2.0-zephyr"

#cmakedefine CONFIG_RTCLAW_AI_API_KEY "@CONFIG_RTCLAW_AI_API_KEY@"
#cmakedefine CONFIG_RTCLAW_AI_API_URL "@CONFIG_RTCLAW_AI_API_URL@"
#cmakedefine CONFIG_RTCLAW_AI_MODEL "@CONFIG_RTCLAW_AI_MODEL@"

#endif /* CLAW_GEN_CONFIG_H */
